site_name: mkdocs test site
site_description: A simple site to demostrate mkdocs functionality for personal reference.
site_author: harryeslick
# repo_url: https://github.com/DPIRD-FSI/pydst

theme:
    palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/link
          name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        # primary: custom
        # accent: custom
        toggle:
          icon: material/toggle-switch
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/toggle-switch-off
          name: Switch to system preference

    name: material
    icon:
        repo: fontawesome/brands/github
    # logo: https:
    # favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    # font:
    #     text: Google Sans
    #     code: Regular

plugins:
    - search
    - mkdocstrings
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          allow_errors: false
          # ignore:
          # execute_ignore:

markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

nav:
    - Home: index.md
    # - Installation: installation.md
    # - Usage: usage.md
    # - Contributing: contributing.md
    # - FAQ: faq.md
    # - Changelog: changelog.md
    - Report Issues: https://github.com/harryeslick/mkdocs_example/issues
    - API Reference:
          - dummy package: mkdocstring_example.md

    - ipynb-examples:
          - notebooks/example.ipynb


extra_css:
  - style.css
