name: Deploy MkDocs Site

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material mkdocstrings mkdocs-jupyter pymdown-extensions
          pip install geodatasets geopandas plotly folium matplotlib mapclassify
          pip install mkdocstrings-python

      - name: Deploy
        run: |
          mkdocs gh-deploy --force


        # uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}